version: "3.1"
services:
  postgres:
    image: postgres:latest
    container_name: postgresC
    ports:
      - "2325:5432"
    environment:
      POSTGRES_DB: shopdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmqC
    ports:
      - "5672:5672" # RabbitMQ default port
      - "15672:15672" # RabbitMQ management interface
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
