server:
  port: 2323
  servlet:
    contextPath: /api/appointment

spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/appointmentDB
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enable: true